spring:
  application:
    name: cloud-serial-consumer
server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/
