server:
  port: 9001
spring:
  application:
    name: sulin-eureka-server-9001
eureka:
  instance:
    hostname: localhost
  client:
#    表示是否从其他eureka-server获取注册信息，如果是单点server，则不需要配置
    fetch-registry: false
#    表示是否需要向服务中心注册自己
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
  server:
    #    关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
    a-s-g-update-interval-ms: 3

