spring:
  application:
    name: cloud-serial-consumer
server:
  port: 11111
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 500  #并发执行的最大线程数，默认10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000

feign:
  hystrix:
    enabled: true
  client:
    config:
      cloud-payment-service:
        loggerLever: FULL
logging:
  level:
    club.sulinxx.spring.cloud.feign.PaymentClient: debug
#    暴露dashboard 端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

turbine:
#  要监控的微服务列表
  app-config: cloud-payment-service
  cluster-name-expression: "'default'"
